name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run Docker container
      run: |
        # Build with consistent tag
        docker build -t my-app .
        
        # Run in background with port mapping
        docker run -d -p 8080:8080 --name running-app my-app
        
        # Wait for container to start
        sleep 5
        
        # Verify container is running
        docker ps
        
        # Test local access
        curl -v http://localhost:8080 || echo "Local service not responding"
    
    - name: Set up SSH port forwarding with Serveo
      run: |
        # Install SSH if needed (usually not necessary)
        which ssh || sudo apt-get update && sudo apt-get install -y openssh-client
        
        # Forward port
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o PasswordAuthentication=no \
            -R 80:localhost:8080 serveo.net
